language: java
matrix:
  include:
    - jdk: openjdk8
      install: true
    - jdk: openjdk11
      install: true
    - jdk: openjdk14
      install: true
  include:
    - name: NonDex
    - jdk: openjdk8
      jdk: openjdk8
      script: sh nondex.sh
before_install:
    - sudo apt-get update -qq
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean test
    - if [ "$TRAVIS_EVENT_TYPE" == "cron" ] || [ ! -z $nondextests ]; then mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn edu.illinois:nondex-maven-plugin:1.1.2:nondex -DnondexSeed=$RANDOM -DnondexRuns=10 -DfailIfNoTests=false -Dtest=$nondextests > /dev/null 2>&1 ; fi
  - if [ -d ".nondex" ]; then flakyTests=$(awk ' !x[$0]++' .nondex/*/failures); fi
  - if [ ! -z "$flakyTests" ]; then printf "Found flaky tests:\n$flakyTests \n" ; exit 1 ; fi
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
        - 0.5-branch
        - 0.6-branch
        - 0.7-branch
        - 0.8-branch
notifications:
    email:
        recipients:
        - pholser@alumni.rice.edu

before_script:
  - if [[ -z $TRAVIS_COMMIT_RANGE ]]; then TRAVIS_COMMIT_RANGE=$(git rev-parse master)...$(git rev-parse HEAD); fi
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then nondextests=""; else nondextests=$(git diff --name-status $TRAVIS_COMMIT_RANGE | grep /test/ | sed -e 's;.*test/java/;;' -e 's/.java//' -e 's;/;.;g' | tr '\n' ','); fi
